[theme]
primaryColor = "#e50914"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#111111"
textColor = "#eeeeee"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
magicEnabled = false
